// <auto-generated />
using System;
using DataAccess.Contexts.DockerDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DockerDbContext))]
    [Migration("20240715022925_FriendsUseEntraId")]
    partial class FriendsUseEntraId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.DockerDb.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlphaChannelFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("alpha_channel_flag");

                    b.Property<bool>("AnimatedFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("animated_flag");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<int>("Height")
                        .HasColumnType("int(11)")
                        .HasColumnName("height");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.Property<int>("Width")
                        .HasColumnType("int(11)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "game_id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique();

                    b.ToTable("artwork");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Companies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DeveloperFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("developer_flag");

                    b.Property<DateOnly>("FoundedDate")
                        .HasColumnType("date")
                        .HasColumnName("founded_date");

                    b.Property<string>("ImageFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("PublisherFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("publisher_flag");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id1");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Cover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AlphaChannelFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("alpha_channel_flag");

                    b.Property<bool>("AnimatedFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("animated_flag");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<int>("Height")
                        .HasColumnType("int(11)")
                        .HasColumnName("height");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.Property<int>("Width")
                        .HasColumnType("int(11)")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "game_id")
                        .HasDatabaseName("game_id1");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id2");

                    b.ToTable("cover");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GameSelfLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildGameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("child_game_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("GameSelfLinkTypeLookupId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_self_link_type_lookup_id");

                    b.Property<int>("ParentGameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("parent_game_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameSelfLinkTypeLookupId" }, "game_self_link_game_self_link_type_lookup_link_ibfk_1");

                    b.HasIndex(new[] { "ParentGameId" }, "game_self_link_games_link_ibfk_1");

                    b.HasIndex(new[] { "ChildGameId" }, "game_self_link_games_link_ibfk_2");

                    b.ToTable("game_self_link");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GameSelfLinkTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("game_self_link_type_lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DLC",
                            CreatedBy = "181972b7-1d32-4b26-bd1f-0bfc7b9d9f9f",
                            CreatedDate = new DateTime(2024, 7, 14, 19, 29, 25, 441, DateTimeKind.Local).AddTicks(4117),
                            Description = "Downloadable Content",
                            Name = "DLC"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EXPANS",
                            CreatedBy = "181972b7-1d32-4b26-bd1f-0bfc7b9d9f9f",
                            CreatedDate = new DateTime(2024, 7, 14, 19, 29, 25, 441, DateTimeKind.Local).AddTicks(4159),
                            Description = "Expansion",
                            Name = "Expansion"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("ParentGameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("parent_game_id");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id3");

                    b.ToTable("games");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GamesCompaniesLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompaniesId")
                        .HasColumnType("int(11)")
                        .HasColumnName("companies_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<bool>("DeveloperFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("developer_flag");

                    b.Property<int>("GamesId")
                        .HasColumnType("int(11)")
                        .HasColumnName("games_id");

                    b.Property<bool>("PortingFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("porting_flag");

                    b.Property<bool>("PublisherFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("publisher_flag");

                    b.Property<bool>("SupportingFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("supporting_flag");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CompaniesId" }, "companies_id");

                    b.HasIndex(new[] { "GamesId" }, "games_id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id4");

                    b.ToTable("games_companies_link");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GamesGenresLookupLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<int>("GenreLookupId")
                        .HasColumnType("int(11)")
                        .HasColumnName("genre_lookup_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "game_id")
                        .HasDatabaseName("game_id2");

                    b.HasIndex(new[] { "GenreLookupId" }, "genre_lookup_id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id5");

                    b.ToTable("games_genres_lookup_link");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GamesPlatformsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int(11)")
                        .HasColumnName("platform_id");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "game_id")
                        .HasDatabaseName("game_id3");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id6");

                    b.HasIndex(new[] { "PlatformId" }, "platform_id");

                    b.ToTable("games_platforms_link");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GenresLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("mediumtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id7");

                    b.ToTable("genres_lookup");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Platforms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("ImageFilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id8");

                    b.ToTable("platforms");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecordCommentVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("EmojiValue")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emoji_value");

                    b.Property<int?>("NumericalValue")
                        .HasColumnType("int(11)")
                        .HasColumnName("numerical_value");

                    b.Property<int>("PlayRecordCommentId")
                        .HasColumnType("int(11)")
                        .HasColumnName("play_record_comment_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedBy" }, "created_by");

                    b.HasIndex(new[] { "PlayRecordCommentId" }, "play_record_comment_id");

                    b.ToTable("play_record_comment_vote");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecordComments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("comment_text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("PlayRecordId")
                        .HasColumnType("int(11)")
                        .HasColumnName("play_record_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id9");

                    b.HasIndex(new[] { "PlayRecordId" }, "play_record_id");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("play_record_comments");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("CompletedFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completed_flag");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("GameId")
                        .HasColumnType("int(11)")
                        .HasColumnName("game_id");

                    b.Property<int?>("HoursPlayed")
                        .HasColumnType("int(11)")
                        .HasColumnName("hours_played");

                    b.Property<string>("PlayDescription")
                        .HasColumnType("mediumtext")
                        .HasColumnName("play_description");

                    b.Property<int?>("Rating")
                        .HasColumnType("int(11)")
                        .HasColumnName("rating");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GameId" }, "game_id")
                        .HasDatabaseName("game_id4");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id10");

                    b.HasIndex(new[] { "UserId" }, "user_id")
                        .HasDatabaseName("user_id1");

                    b.ToTable("play_records");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.UserRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChildUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("child_user_id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<int>("RelationshipTypeLookupId")
                        .HasColumnType("int(11)")
                        .HasColumnName("relationship_type_lookup_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChildUserId" }, "child_user_id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id11");

                    b.HasIndex(new[] { "RelationshipTypeLookupId" }, "relationship_type_lookup_id");

                    b.HasIndex(new[] { "CreatedBy" }, "user_id")
                        .HasDatabaseName("user_id2");

                    b.ToTable("user_relationship");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.UserRelationshipTypeLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id12");

                    b.ToTable("user_relationship_type_lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FRIEND",
                            CreatedBy = "181972b7-1d32-4b26-bd1f-0bfc7b9d9f9f",
                            CreatedDate = new DateTime(2024, 7, 14, 19, 29, 25, 441, DateTimeKind.Local).AddTicks(4292),
                            Description = "One directional friend link",
                            Name = "Friend"
                        },
                        new
                        {
                            Id = 2,
                            Code = "IGNORE",
                            CreatedBy = "181972b7-1d32-4b26-bd1f-0bfc7b9d9f9f",
                            CreatedDate = new DateTime(2024, 7, 14, 19, 29, 25, 441, DateTimeKind.Local).AddTicks(4296),
                            Description = "One directional ignore.",
                            Name = "Ignore"
                        });
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdminFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("admin_flag");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("ImageFilePath")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_file_path");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Id" }, "id")
                        .IsUnique()
                        .HasDatabaseName("id13");

                    b.ToTable("users");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Artwork", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Games", "Game")
                        .WithMany("Artwork")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("artwork_games_ibfk_1");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Cover", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Games", "Game")
                        .WithMany("Cover")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("cover_games_ibfk_1");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GameSelfLink", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Games", "ChildGame")
                        .WithMany("GameSelfLinkChildGame")
                        .HasForeignKey("ChildGameId")
                        .IsRequired()
                        .HasConstraintName("game_self_link_games_link_ibfk_2");

                    b.HasOne("DataAccess.Models.DockerDb.GameSelfLinkTypeLookup", "GameSelfLinkTypeLookup")
                        .WithMany("GameSelfLink")
                        .HasForeignKey("GameSelfLinkTypeLookupId")
                        .IsRequired()
                        .HasConstraintName("game_self_link_game_self_link_type_lookup_link_ibfk_1");

                    b.HasOne("DataAccess.Models.DockerDb.Games", "ParentGame")
                        .WithMany("GameSelfLinkParentGame")
                        .HasForeignKey("ParentGameId")
                        .IsRequired()
                        .HasConstraintName("game_self_link_games_link_ibfk_1");

                    b.Navigation("ChildGame");

                    b.Navigation("GameSelfLinkTypeLookup");

                    b.Navigation("ParentGame");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GamesCompaniesLink", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Companies", "Companies")
                        .WithMany("GamesCompaniesLink")
                        .HasForeignKey("CompaniesId")
                        .IsRequired()
                        .HasConstraintName("games_companies_link_ibfk_2");

                    b.HasOne("DataAccess.Models.DockerDb.Games", "Games")
                        .WithMany("GamesCompaniesLink")
                        .HasForeignKey("GamesId")
                        .IsRequired()
                        .HasConstraintName("games_companies_link_ibfk_1");

                    b.Navigation("Companies");

                    b.Navigation("Games");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GamesGenresLookupLink", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Games", "Game")
                        .WithMany("GamesGenresLookupLink")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("games_genres_lookup_link_ibfk_1");

                    b.HasOne("DataAccess.Models.DockerDb.GenresLookup", "GenreLookup")
                        .WithMany("GamesGenresLookupLink")
                        .HasForeignKey("GenreLookupId")
                        .IsRequired()
                        .HasConstraintName("games_genres_lookup_link_ibfk_2");

                    b.Navigation("Game");

                    b.Navigation("GenreLookup");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GamesPlatformsLink", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Games", "Game")
                        .WithMany("GamesPlatformsLink")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("games_platforms_link_ibfk_1");

                    b.HasOne("DataAccess.Models.DockerDb.Platforms", "Platform")
                        .WithMany("GamesPlatformsLink")
                        .HasForeignKey("PlatformId")
                        .IsRequired()
                        .HasConstraintName("games_platforms_link_ibfk_2");

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecordCommentVote", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.PlayRecordComments", "PlayRecordComment")
                        .WithMany("PlayRecordCommentVote")
                        .HasForeignKey("PlayRecordCommentId")
                        .IsRequired()
                        .HasConstraintName("play_record_comment_vote_ibfk_1");

                    b.Navigation("PlayRecordComment");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecordComments", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.PlayRecords", "PlayRecord")
                        .WithMany("PlayRecordComments")
                        .HasForeignKey("PlayRecordId")
                        .IsRequired()
                        .HasConstraintName("play_record_comments_ibfk_2");

                    b.Navigation("PlayRecord");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecords", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.Games", "Game")
                        .WithMany("PlayRecords")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("play_records_ibfk_2");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.UserRelationship", b =>
                {
                    b.HasOne("DataAccess.Models.DockerDb.UserRelationshipTypeLookup", "RelationshipTypeLookup")
                        .WithMany("UserRelationship")
                        .HasForeignKey("RelationshipTypeLookupId")
                        .IsRequired()
                        .HasConstraintName("user_relationship_ibfk_3");

                    b.Navigation("RelationshipTypeLookup");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Companies", b =>
                {
                    b.Navigation("GamesCompaniesLink");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GameSelfLinkTypeLookup", b =>
                {
                    b.Navigation("GameSelfLink");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Games", b =>
                {
                    b.Navigation("Artwork");

                    b.Navigation("Cover");

                    b.Navigation("GameSelfLinkChildGame");

                    b.Navigation("GameSelfLinkParentGame");

                    b.Navigation("GamesCompaniesLink");

                    b.Navigation("GamesGenresLookupLink");

                    b.Navigation("GamesPlatformsLink");

                    b.Navigation("PlayRecords");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.GenresLookup", b =>
                {
                    b.Navigation("GamesGenresLookupLink");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.Platforms", b =>
                {
                    b.Navigation("GamesPlatformsLink");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecordComments", b =>
                {
                    b.Navigation("PlayRecordCommentVote");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.PlayRecords", b =>
                {
                    b.Navigation("PlayRecordComments");
                });

            modelBuilder.Entity("DataAccess.Models.DockerDb.UserRelationshipTypeLookup", b =>
                {
                    b.Navigation("UserRelationship");
                });
#pragma warning restore 612, 618
        }
    }
}
