// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models
{
    [Table("game_raw")]
    public partial class GameRaw
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("name", TypeName = "text")]
        public string Name { get; set; } = null!;
        [Column("age_ratings", TypeName = "text")]
        public string? AgeRatings { get; set; }
        [Column("aggregated_rating")]
        public double? AggregatedRating { get; set; }
        [Column("aggregated_rating_count", TypeName = "int(11)")]
        public int? AggregatedRatingCount { get; set; }
        [Column("alternative_names", TypeName = "text")]
        public string? AlternativeNames { get; set; }
        [Column("artworks", TypeName = "text")]
        public string? Artworks { get; set; }
        [Column("bundles", TypeName = "text")]
        public string? Bundles { get; set; }
        [Column("category", TypeName = "int(11)")]
        public int? Category { get; set; }
        [Column("collection", TypeName = "int(11)")]
        public int? Collection { get; set; }
        [Column("collections", TypeName = "text")]
        public string? Collections { get; set; }
        [Column("cover", TypeName = "int(11)")]
        public int? Cover { get; set; }
        [Column("created_at", TypeName = "int(11)")]
        public int? CreatedAt { get; set; }
        [Column("display")]
        public bool? Display { get; set; }
        [Column("dlcs", TypeName = "text")]
        public string? Dlcs { get; set; }
        [Column("expanded_games", TypeName = "text")]
        public string? ExpandedGames { get; set; }
        [Column("expansions", TypeName = "text")]
        public string? Expansions { get; set; }
        [Column("external_games", TypeName = "text")]
        public string? ExternalGames { get; set; }
        [Column("first_release_date", TypeName = "int(11)")]
        public int? FirstReleaseDate { get; set; }
        [Column("forks", TypeName = "text")]
        public string? Forks { get; set; }
        [Column("franchise", TypeName = "int(11)")]
        public int? Franchise { get; set; }
        [Column("franchises", TypeName = "text")]
        public string? Franchises { get; set; }
        [Column("game_engines", TypeName = "text")]
        public string? GameEngines { get; set; }
        [Column("game_localizations", TypeName = "text")]
        public string? GameLocalizations { get; set; }
        [Column("game_modes", TypeName = "text")]
        public string? GameModes { get; set; }
        [Column("genres", TypeName = "text")]
        public string? Genres { get; set; }
        [Column("hypes", TypeName = "int(11)")]
        public int? Hypes { get; set; }
        [Column("involved_companies", TypeName = "text")]
        public string? InvolvedCompanies { get; set; }
        [Column("keywords", TypeName = "text")]
        public string? Keywords { get; set; }
        [Column("language_supports", TypeName = "text")]
        public string? LanguageSupports { get; set; }
        [Column("multiplayer_modes", TypeName = "text")]
        public string? MultiplayerModes { get; set; }
        [Column("parent_game", TypeName = "int(11)")]
        public int? ParentGame { get; set; }
        [Column("platforms", TypeName = "text")]
        public string? Platforms { get; set; }
        [Column("player_perspectives", TypeName = "text")]
        public string? PlayerPerspectives { get; set; }
        [Column("ports", TypeName = "text")]
        public string? Ports { get; set; }
        [Column("rating")]
        public double? Rating { get; set; }
        [Column("rating_count", TypeName = "int(11)")]
        public int? RatingCount { get; set; }
        [Column("release_dates", TypeName = "text")]
        public string? ReleaseDates { get; set; }
        [Column("remakes", TypeName = "text")]
        public string? Remakes { get; set; }
        [Column("remasters", TypeName = "text")]
        public string? Remasters { get; set; }
        [Column("screenshots", TypeName = "text")]
        public string? Screenshots { get; set; }
        [Column("similar_games", TypeName = "text")]
        public string? SimilarGames { get; set; }
        [Column("slug", TypeName = "text")]
        public string? Slug { get; set; }
        [Column("standalone_expansions", TypeName = "text")]
        public string? StandaloneExpansions { get; set; }
        [Column("status", TypeName = "int(11)")]
        public int? Status { get; set; }
        [Column("storyline", TypeName = "text")]
        public string? Storyline { get; set; }
        [Column("summary", TypeName = "text")]
        public string? Summary { get; set; }
        [Column("tags", TypeName = "text")]
        public string? Tags { get; set; }
        [Column("themes", TypeName = "text")]
        public string? Themes { get; set; }
        [Column("total_rating")]
        public double? TotalRating { get; set; }
        [Column("total_rating_count", TypeName = "int(11)")]
        public int? TotalRatingCount { get; set; }
        [Column("updated_at", TypeName = "int(11)")]
        public int? UpdatedAt { get; set; }
        [Column("version_parent", TypeName = "int(11)")]
        public int? VersionParent { get; set; }
        [Column("version_title", TypeName = "text")]
        public string? VersionTitle { get; set; }
        [Column("videos", TypeName = "text")]
        public string? Videos { get; set; }
        [Column("websites", TypeName = "text")]
        public string? Websites { get; set; }
    }
}