# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services: 
  game-api-server:
    network_mode: bridge
    container_name: 'game-api-server'
    env_file:
      - web-variables.env
    build:
      context: .
      target: final
    ports:
      - 8080:8080
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db: #docker exec -it mariadb mariadb -u user -p
    network_mode: bridge
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    container_name: 'mariadb'
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariadbvolume:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadbvolume:
# secrets:
#   db-password:
#     file: db/password.txt

