// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models.NickDb;

[Table("genres_lookup")]
[Index("Id", Name = "id", IsUnique = true)]
public partial class GenresLookup
{
    [Key]
    [Column("id", TypeName = "int(11)")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(50)]
    public string? Name { get; set; }

    [Column("code")]
    [StringLength(8)]
    public string? Code { get; set; }

    [Column("description", TypeName = "mediumtext")]
    public string? Description { get; set; }

    [Column("created_by")]
    [StringLength(25)]
    public string CreatedBy { get; set; } = null!;

    [Column("created_date", TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [InverseProperty("GenreLookup")]
    public virtual ICollection<GamesGenresLookupLink> GamesGenresLookupLink { get; set; } = new List<GamesGenresLookupLink>();
}